# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cdd9951e3143e055cf659ca47e7da6b2"
name = "rocart"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_checkouts,read_checkouts,read_customers,write_customers,read_orders,write_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
